version: '3'
services:
  postgresdb:
    image: postgres
    ports:
      - 8081:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=record

  myapp:
    image: favour-app:3.0
    ports:
      - 8080:8080
